### ISSUE TITLE
Low frame rate with WOLK Patch 3.4.2

### ISSUE THREAD

**Issue by cwland** [shirsig/npcscan#26]
When this add-on is enabled with the latest patch, the frame rate drops so low the game is unplayable.

**Comment by shirsig** [comment]
Interestingly it was turning off the sound through the cvar interface for the attempted targeting that was causing the slowdown. I'm not sure now if that was even ever needed for classic (in vanilla/1.12.1 it was needed because it was actually targeting, not just attempting to target, which was causing targeting sounds) so I've just removed it and I haven't noticed any issues.

**Comment by kriminy** [comment]
This issue is also present in the new Classic Era PTR (toc 1.14.4). I'm not sure how to fix this, but I'll try to search and comment it out.

edit:
I commented out lines 40, 41, and 43 of unitscan.lua. Seems to work. Thank you so much!

**Comment by shirsig** [comment]
Thanks for pointing that out. I applied the same fix to the classic era version.
