### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by Suamere** [shirsig/npcscan#4]
I was just going to test this, and so I waited for a rare target to be killed (by somebody stronger, lawl).  Once that target was killed, I added him to the list.  It immediately set off the alarm and cleared the list.

If there is a way to check the target if it is alive, or HP, or something so it doesn't false positive, that would be a solid improvement.  Either way, this is a great addon.

**Comment by shirsig** [comment]
There isn't. That's why targets are removed once detected.
I mean, it's possible to make these checks for the target but only after targeting it, with all the negative consequences of changing targets (stopping auto attack, removing combo points etc.).
My other addon that does target scanning (https://github.com/shirsig/sentry) uses a different approach where it keeps its targets and keeps rescanning even if they're invalid. However it's a pvp addon with different requirements and there are some trade-offs. For example it will only try to scan if nothing bad will happen when changing targets and it has a timeout between scans to avoid performance issues on rescanning invalid targets very frequently, but of course you wouldn't want to miss a rare spawn because you were auto attacking something or because the scanning is on a 30 second cooldown so that wouldn't work for this addon.
