### ISSUE TITLE
Just doesn't work (Classic)

### ISSUE THREAD

**Issue by dredtaur** [shirsig/npcscan#7]
First usage received warning of too many errors and suggested disabling addons. I did not disable, and tried it anyway. Result was it accepted the name to search for, but did not recognize the rare when it appeared. I tried with a normal mob name and it did not recognize it either.

Any way to TEST it's working properly? Eg. go to a specific place and scan for a specific mob?

**Comment by shirsig** [comment]
This can never work. It's simply not possible with the classic api.

**Comment by shirsig** [comment]
As someone pointed out the error for disallowed actions for TargetUnit only happens when the unit was targetable, so I was able to make it partially work. It's still very limited compared to vanilla.
* There is no 3d unit model.
* The found unit is not targeted.
* Clicking the button does not target it either (apparently targeting by name is not possible for addons, not even with secureactionbuttons)

(This is the **retail** branch btw)
